### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Ispirett**

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
### Good work 🏆
Cool animation 👏🏻Rest of the stuff looks nice as well. In CSS, mostly `id` is used instead of classes. Kindly refactor your code and use `id` only when it's needed(in scrollspy and when working with JavaScript mostly). And fix conflict as well for stickler.
Once fixed, kindly resubmit and add me(Inzi) as project reviewer. Happy Coding 😊

**Comment by Ispirett** [comment]
Thanks for the feedback we worked hard :) The changes you requested were
made.

**Review by inhaq — APPROVED** [review]
### 👍🏻for this project
Congrats on completing this project 👏🏻go ahead and submit a project completion form.
I would strongly recommend to not use `id` in the next projects as well, good work on refactoring this project. Good luck with the next project 🎉

**Comment by Ispirett** [comment]
thank you very much :))

**Pull request merged**
